char = ord ('B')
print(char,"is the integer equivalent of char('B')")
char = ord ('C')
print(char,"is the integer equivalent of char('C')")
char = ord ('D')
print(char,"is the integer equivalent of char('D')")
char = ord ('b')
print(char,"is the integer equivalent of char('b')")
char = ord  ('c')
print(char,"is the integer equivalent of char('c')")
char = ord ('d')
print(char,"is the integer equivalent of char('d')")
char = ord ('0')
print(char,"is the integer equivalent of char('0')")
char = ord ('1') 
print(char,"is the integer equivalent of char('1')")
char = ord ('2') 
print(char,"is the integer equivalent of char('2')")
char = ord ('$')
print(char,"is the integer equivalent of char('$')")
char = ord  ('*')
print(char,"is the integer equivalent of char('*')")
char = ord ('+')
print(char,"is the integer equivalent of char('+')")
char = ord  (' ')
print(char,"is the integer equivalent of char(' ')")